alter table public.push_subscriptions
  add column if not exists preferred_hour smallint not null default 10
  check (preferred_hour between 0 and 23);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  appliance_id uuid not null references public.appliances(id) on delete cascade,
  due_date date not null,
  sent_at timestamptz not null default now(),
  unique (subscription_id, appliance_id, due_date)
);

create index if not exists notification_deliveries_sent_at_idx
  on public.notification_deliveries(sent_at);

alter table public.notification_deliveries enable row level security;
revoke all on public.notification_deliveries from anon, authenticated;
